---
abstract: 'a demo website for Catalyst framework'
author:
  - 'Jeff Mo - <mo0118@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Cinema
no_index:
  directory:
    - inc
    - t
requires:
  Captcha::reCAPTCHA: 0
  Catalyst: 5.7002
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Controller: 0
  Catalyst::Controller::FormBuilder: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::View::TT: 0
  DBD::SQLite: 0
  DBIx::Class: 0
  DBIx::Class::Schema: 0
  HTTP::Date: 0
  Mail::Mailer: 0
  YAML: 0
  YAML::XS: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.171
